name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Run Test Cases
        run: mvn clean '-Dtest=*Test' -Djacoco.destFile=target/jacoco.exec test

      - name: Upload jacoco exec test results
        uses: actions/upload-artifact@v2
        with:
          name: tests-jacoco
          path: target/jacoco.exec

      - name: Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
